plugins {
    id 'groovy'
    id 'java'
    id "com.github.node-gradle.node" version "7.1.0"
    // For static null checking:
    id "net.ltgt.errorprone" version "3.1.0"
}

group 'org.gleethos'
version '0.0.0'
sourceCompatibility = '21'

var REACT_SKIN_LOCATION = 'src/main/web-portal'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    google()
}

dependencies {

    // JSpecify
    errorprone "com.uber.nullaway:nullaway:0.12.8"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
    errorprone "com.google.errorprone:error_prone_core:2.27.0"
    implementation group: 'com.google.errorprone', name: 'error_prone_annotations', version: '2.27.0'
    implementation 'org.jspecify:jspecify:1.0.0'


    implementation 'javax.websocket:javax.websocket-api:1.1'
    implementation 'org.eclipse.jetty:jetty-servlet:9.4.57.v20241219'
    implementation 'org.eclipse.jetty.websocket:websocket-server:9.4.57.v20241219'
    implementation 'org.eclipse.jetty:jetty-server:9.4.57.v20241219'

    implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.50.3.0'
    implementation group: 'io.github.globaltcad', name: 'swing-tree', version:'0.14.0'

    // Testing with Spock :
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'    // mandatory dependencies for using Spock

    testImplementation 'org.apache.groovy:groovy'
    testImplementation platform('org.spockframework:spock-bom:2.3-groovy-4.0')
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
    testImplementation 'com.athaydes:spock-reports:2.5.1-groovy-4.0'

    implementation 'com.formdev:flatlaf-intellij-themes:3.6.1'
    implementation 'com.formdev:flatlaf:3.6.1' // Looks better than regular swing :)
    implementation group: 'com.metsci.ext.com.kitfox.svg', name: 'svg-salamander', version: '0.1.19'

    implementation group: 'org.json', name: 'json', version: '20250517'

    // Command line parsing :
    implementation 'org.jcommander:jcommander:2.0'

    // Logging :
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.17'
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.17'

    // Integration test with Geb and Spock :
    testImplementation group: 'org.gebish', name: 'geb-spock', version: '7.0'
    testImplementation group: 'org.seleniumhq.selenium', name: 'selenium-firefox-driver', version: '4.34.0'

}

tasks.withType(JavaCompile).configureEach {
    // remove the if condition if you want to run NullAway on test code
    if (!name.toLowerCase().contains("test")) {
        options.errorprone {
            check("NullAway", net.ltgt.gradle.errorprone.CheckSeverity.ERROR)
            option("NullAway:AnnotatedPackages", "")
        }
    } else {
        options.errorprone {
            check("NullAway", net.ltgt.gradle.errorprone.CheckSeverity.WARN)
            option("NullAway:AnnotatedPackages", "")
        }
    }
}

// Read more about how to configure the plugin from
// https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md
node {
    // Whether to download and install a specific Node.js version or not
    // If false, it will use the globally installed Node.js
    // If true, it will download node using above parameters
    // Note that npm is bundled with Node.js
    download = true

    // Version of node to download and install (only used if download is true)
    // It will be unpacked in the workDir
    version = "22.18.0"

    // Version of npm to use
    // If specified, installs it in the npmWorkDir
    // If empty, the plugin will use the npm command bundled with Node.js
    npmVersion = ""

    // Version of Yarn to use
    // Any Yarn task first installs Yarn in the yarnWorkDir
    // It uses the specified version if defined and the latest version otherwise (by default)
    yarnVersion = ""

    // Base URL for fetching node distributions
    // Only used if download is true
    // Change it if you want to use a mirror
    // Or set to null if you want to add the repository on your own.
    distBaseUrl = "https://nodejs.org/dist"

    // Specifies whether it is acceptable to communicate with the Node.js repository over an insecure HTTP connection.
    // Only used if download is true
    // Change it to true if you use a mirror that uses HTTP rather than HTTPS
    // Or set to null if you want to use Gradle's default behaviour.
    allowInsecureProtocol = null

    // The npm command executed by the npmInstall task
    // By default it is install but it can be changed to ci
    npmInstallCommand = "install"

    // The directory where Node.js is unpacked (when download is true)
    workDir = file("${project.projectDir}/.gradle/nodejs")

    // The directory where npm is installed (when a specific version is defined)
    npmWorkDir = file("${project.projectDir}/.gradle/npm")

    // The directory where yarn is installed (when a Yarn task is used)
    yarnWorkDir = file("${project.projectDir}/.gradle/yarn")

    // The Node.js project directory location
    // This is where the package.json file and node_modules directory are located
    // By default it is at the root of the current project
    nodeProjectDir = file("${project.projectDir}/$REACT_SKIN_LOCATION")

    // Whether the plugin automatically should add the proxy configuration to npm and yarn commands
    // according the proxy configuration defined for Gradle
    // Disable this option if you want to configure the proxy for npm or yarn on your own
    // (in the .npmrc file for instance)
    nodeProxySettings = ProxySettings.SMART
}

// Build the project locally
tasks.register('appNpmBuild', NpmTask) {
    description = "Builds production version of tribee-portal"
    workingDir = file("${project.projectDir}/$REACT_SKIN_LOCATION")
    args = ["run", "build"]
}

// Copies the project to the service folder
tasks.register('copyWebAppToWebRoot', Copy) {
    dependsOn appNpmBuild
    from "$REACT_SKIN_LOCATION/build"
    into 'src/main/resources/web/.'
}

/*
    Combines build and copy tasks!
    Use this for rebuilding the react frontend
    (rebuild the react app and copy the build folder to the resources folder)
*/
tasks.register('buildWebApp', NpmTask) {
    description = "Builds production version of tribee-portal"
    dependsOn appNpmBuild
    dependsOn copyWebAppToWebRoot
}

appNpmBuild.dependsOn npmInstall
compileJava.dependsOn copyWebAppToWebRoot
processResources.dependsOn copyWebAppToWebRoot

// A task which starts the 'Main' class of the project with a certain set of arguments
// Note that this is done in a new thread, so the task will finish immediately and we can run other tasks in parallel
tasks.register('runServer', JavaExec) {
    main = 'Main'
    classpath = sourceSets.main.runtimeClasspath
    args = ['--start-server', 'true', '--port', '8080', '--headless', 'true']
}

// A task for executing the react tests:
tasks.register('appNpmTest', NpmTask) { // TODO: Make this depend on the server task!
    description = "Runs the react tests"
    workingDir = file("${project.projectDir}/$REACT_SKIN_LOCATION")
    args = ["run", "test"]
}

test {
    useJUnitPlatform()
}