package dal.impl;

import dal.api.DataBaseEntity;
import dal.api.Value;
import org.jspecify.annotations.NullMarked;
import sprouts.Tuple;

import java.lang.reflect.Method;
import java.lang.reflect.RecordComponent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@NullMarked
record ValueTable(
    Tuple<EntityTableField> fields,
    Class<? extends Value> valueType
) implements EntityTable
{
    public static final String HASH_FIELD_NAME = "hash_code";
    public static final String USAGE_FIELD_COUNTER = "usages";


    static ValueTable of(
        Class<? extends Value> valueType,
        Tuple<Class<? extends DataBaseEntity>> otherModels
    ) {
        // We expect something like this:
        /*
            public record School(
                String name,
                Tuple<Student> students,
                Tuple<Teacher> teachers
            ) {}
        */
        // First we need to check if it is a record
        if (!valueType.isRecord()) {
            throw new IllegalArgumentException("The class " + valueType.getName() + " is not a record");
        }
        // Then we need to check that it implements Value
        if (!Value.class.isAssignableFrom(valueType))
            throw new IllegalArgumentException(
                    "The interface " + valueType.getName() + " is not a subclass of " + Value.class.getName()
            );

        // Now we can get the fields
        Method[] methods = valueType.getMethods();
        List<EntityTableField> fields = new ArrayList<>();
        for (Method method : methods) {
            /*
                We are working with a record here,
                so we only want the methods which return a field of the record.
             */
            // Skip static methods, void methods, and methods with parameters
            if ( method.getReturnType().equals(Void.class) || method.getParameterCount() > 0) {
                continue;
            }

            // Check if it's a record component (i.e., a getter for a record field)
            // In records, component methods are generated by the compiler and are not annotated
            // So we rely on naming convention: method name matches field name (e.g., "name", "students")
            // But more reliably: we can use the fact that record components are accessible via RecordComponent
            // However, since we don't have RecordComponent here, we can infer via naming and type

            // For simplicity, we assume: if it's a public non-static non-void method with no args
            // and the method name starts with a lowercase letter and matches a field name, it's a component getter
            // But better: use RecordComponent to verify it's actually a record component

            // Alternative: use RecordComponent to get the components of the record
            // This is more accurate than guessing by name
            RecordComponent[] components = valueType.getRecordComponents();
            for (RecordComponent component : components) {
                if (component.getName().equals(method.getName())) {
                    /*
                        The return type must either be a primitive, a record, or a tuple of primitive and/or record.
                     */
                    var field = EntityTableField.ofValue(method, valueType, otherModels);
                    // This method corresponds to a record component
                    fields.add(field);
                    break;
                }
            }
        }
        // Now we prepare the sorted fields list
        List<EntityTableField> sortedFields = ModelTable.sort(fields);
        // Now we add the id field
        sortedFields.add(0, new EntityTableField(
                EntityTable.ID,
                valueType,
                new FieldType.Primitive(Integer.class),
                false
        ));
        sortedFields.add(1, new EntityTableField(
                HASH_FIELD_NAME,
                valueType,
                new FieldType.Primitive(Long.class),
                false
        ));
        sortedFields.add(2, new EntityTableField(
                USAGE_FIELD_COUNTER,
                valueType,
                new FieldType.Primitive(Long.class),
                false
        ));

        return new ValueTable(Tuple.of(EntityTableField.class, sortedFields), valueType);
    }

    @Override
    public String getTableName() {
        return AbstractDataBase._tableNameFromClass(valueType);
    }

    @Override
    public Tuple<EntityTableField> getFields() {
        return fields;
    }

    @Override
    public Tuple<Class<? extends DataBaseEntity>> getReferencedModels() {
        List<Class<? extends DataBaseEntity>> referencedModels = new ArrayList<>();
        for (EntityTableField field : fields) {
            if (field.isForeignKey()) {
                referencedModels.add((Class<? extends DataBaseEntity>) field.type().itemType());
            }
        }
        return ((Tuple)Tuple.of(Class.class)).addAll(referencedModels);
    }

    @Override
    public Optional<Class<? extends DataBaseEntity>> entityType() {
        return Optional.of(valueType);
    }

    @Override
    public String createTableStatement() {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE IF NOT EXISTS ");
        sb.append(getTableName());
        sb.append(" (");
        for (EntityTableField field : fields)
            field.asSqlColumn().ifPresent(col -> {
                sb.append(col);
                sb.append(", ");
            });

        sb.delete(sb.length() - 2, sb.length());
        sb.append(");");
        return sb.toString();
    }

    @Override
    public Tuple<Object> getDefaultValues() {
        List<Object> defaultValues = new ArrayList<>();
        for (EntityTableField field : fields) {
            if (field.isForeignKey()) {
                defaultValues.add(null);
            } else {
                defaultValues.add(field.getDefaultValue());
            }
        }
        return Tuple.ofNullable(Object.class, defaultValues);
    }

}
